language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql
env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database teamapi_test;' -U postgres
  - psql -c "CREATE USER zizoh WITH PASSWORD null;" -U postgresql
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi